### ISSUE TITLE
mystic:: Version >= 0.2a2.dev0 is required

### ISSUE THREAD

**Issue by uber1geek** [mmckerns/tutmom#3]
Log:

Found existing installation: mystic 0.2a2.dev0
    Uninstalling mystic-0.2a2.dev0:
      Successfully uninstalled mystic-0.2a2.dev0
  Running setup.py install for mystic ... done
Successfully installed mystic-0.2a2.dev0
UberGeeks-Macbook-Air:tutmom PathFinder$ python check_env.py 
mystic:: Version >= 0.2a2.dev0 is required

**Comment by mmckerns** [comment]
@uber1geek: I'm not seeing this error.  Can you tell me more about your system?  Where did you install `mystic` from?  If you obtain the most recent `mystic` from github, I wouldn't expect to see this issue.  I'd like to try to reproduce your steps so I can verify the error.

Maybe you can also let me know what you see when you do:

```
>>> import mystic
>>> mystic.__version__
```

**Comment by mmckerns** [comment]
I'm closing this as stale.  Latest release is `mystic-0.3.1`, so this should no longer be relevant.
