### ISSUE TITLE
Mystic not compatible with Python 3

### ISSUE THREAD

**Issue by taylorsansom** [mmckerns/tutmom#4]
According to the [mystic docs](https://pypi.python.org/pypi/mystic) it requires ```- python, version >= 2.6, version < 3.0```. Is there a python 3.x workaround or is this a non-critical package for this tutorial?

**Comment by mmckerns** [comment]
`mystic` is compatible with python 3, if you use the version on GitHub.  The current stable release is python 2.x only, however a new release is due today -- so either use the version on GitHub, or wait a few hours for the release.
